[build]
  command = "pnpm build"
  publish = ".svelte-kit/netlify"
  base = "apps/blog"

# Deploy contexts
[context.production]
  command = "pnpm build"

[context.branch-deploy]
  command = "pnpm build"

[context.deploy-preview]
  command = "pnpm build" 